<?php
/**
 * ============================================================================
 * SCHEDULED BACKUP CONFIGURATION
 * ============================================================================
 *
 * DO NOT EDIT THIS FILE!
 * To configure databases to backup, edit config.php instead.
 *
 * This file just loads settings from config.php and builds the backup config.
 */

// Load main config
require_once __DIR__ . '/config.php';

// Use database list from config.php
$databasesToBackup = $DATABASES_TO_BACKUP;

// Determine which server to backup based on environment
if (APP_ENV === 'prod') {
    // PRODUCTION: Backup the production server
    $backupHost = DB_PROD_HOST;
    $backupUser = DB_PROD_USER;
    $backupPass = DB_PROD_PASS;
    $envLabel = 'Prod';
} else {
    // DEVELOPMENT: Backup the local test server
    $backupHost = DB_TEST_HOST;
    $backupUser = DB_TEST_USER;
    $backupPass = DB_TEST_PASS;
    $envLabel = 'Dev';
}

// Base backup directory (from config.php)
$baseBackupDir = BACKUP_DIR;

// Build database configuration array from the list above
$databases = [];
foreach ($databasesToBackup as $dbName) {
    $databases[$dbName] = [
        'host' => $backupHost,
        'user' => $backupUser,
        'password' => $backupPass,
        'backupDir' => $baseBackupDir . $dbName . '\\',
        'filenamePrefix' => $dbName . '-' . $envLabel,
        'enabled' => true
    ];
}

// Return complete configuration
return [
    'databases' => $databases,

    // Retention policy (GFS - Grandfather-Father-Son)
    'retention' => [
        'daily' => 30,     // Keep 30 daily backups
        'monthly' => 12,   // Keep 12 monthly backups (one per month)
        'yearly' => 999    // Keep yearly backups indefinitely
    ],

    // Email notifications (optional - not implemented yet)
    'notifications' => [
        'enabled' => false,
        'onSuccess' => false,
        'onFailure' => true,
        'emailTo' => 'admin@example.com'
    ]
];
?>
